@startuml
header Interop Trouble Ticket Lifecycle \nbased on TMF 621\n"Anomalie Adresse" Use Case


state acknowledged #palegreen
state inProgress #palegreen
state closed #palegreen
state rejected #palegreen
state cancelled #palegreen
state resolved #palegreen
state choice <<choice>>
state held #palegreen
state pending #palegreen

[*] --> acknowledged: Controle de base. \n Syntaxe Ok
[*] --> [*]: Erreur Http. \n Requête invalide ou syntaxe KO

acknowledged -[#green]-> inProgress: <color:#green>Affectation d'une ressource (humaine ou si)
acknowledged -[bold,#green]-> rejected: <color:#green>Validation KO
acknowledged -[bold,#blue]-> cancelled: <color:#blue>Ticket annulé par l'OC

inProgress -[#green]-> pending: <color:#green>l'Oi a besoin d'informations supplémentaires\n<color:#green> pour traiter le ticket
pending -right[#green]-> cancelled: <color:#green>Informations supplémentaires \n <color:#green>non fournies par l'OC
pending -[#blue]-> cancelled: <color:#blue>Ticket annulé \n<color:#blue> par l'OC
pending -[#blue]-> inProgress: <color:#blue>Informations supplémentaires \n<color:#blue>fournies par l'OC
inProgress -[bold,#green]-> cancelled: <color:#green>Ticket annulé par l'OI \n<color:#green> ou doublon \n<color:#green>(rattachement du ticket doublon dans les relationShip)
inProgress -[bold,#blue]-> cancelled: <color:#blue>Ticket annulé \n<color:#blue> par l'OC
inProgress -[bold,#green]-> resolved: <color:#green>Ticket résolu
inProgress -up[#green]-> held: <color:#green>affichage d'un gel interne OI
inProgress -[#green]-> inProgress : <color:#green>Complexity et expectedResolutiondate sont renseignées
held -[#green]-> inProgress: <color:#green>Changement de la date de résolution\n<color:#green> et complexité si nécessaire

resolved -[bold,#blue]-> choice
resolved -[bold,#green]-> closed: Cloture par l'OI si besoin
choice -[bold,#blue]-> inProgress: <color:#blue>Oc refuse la résolution
choice -[bold,#blue]-> closed: <color:#blue>Résolution acceptée

closed -[bold,#black]-> [*]: Fin du processus
cancelled -[bold,#black]-> [*]: Fin du processus
rejected -[bold,#black]-> [*]: Fin du processus

legend
    |= Color |= Type |= Description |
    |<#blue>|    <&arrow-right> | Changement d'état à la demande de l'OC|
    |<#green>|    <&arrow-right> | Changement d'état à la demande de l'OI |
endlegend

@enduml
