@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #Thistle
   BackgroundColor<<Ref>> #LightGrey
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #Grey
   BorderColor #Black
   ArrowColor #Black
}

class Anomalie <<Pivot>> {
    id: String
    href: String
    commentaire_oc: String
    commande_client_final_oc: String
    creationDate: Datetime
    type: String
    complexite: String
}

class Creation <<Pivot>> {
    adresse: Adresse
    adresse_creee: AdresseRef[]
}
Anomalie <|-- Creation
Creation *-- "1" Adresse
Creation *-- "n" AdresseRef

class CreationImmeubleNeuf <<Pivot>> {
    adresse: AdresseComplementsSpecifiques
}
note left:  Une creation d'imb neuf aura une adresse de creation \net des complements
CreationImmeubleNeuf *-- "1" AdresseComplementsSpecifiques
Creation <|-- CreationImmeubleNeuf

class Modification <<Pivot>> {
    adresse_initiale: AdresseRef
    adresse_cible: Adresse
}
class AnomalieEnMasse <<Pivot>> {
    adresses_initiales: AdresseRef[]
    champs_anomalie: string[]
}
Anomalie <|-- Modification
Anomalie <|-- AnomalieEnMasse
Modification *-- "1" Adresse
Modification *-- "1" AdresseRef
AnomalieEnMasse *-- "1-*" AdresseRef

class Adresse {
    code_adresse: String
    code_insee: String
    code_voie_rivoli: String
    numero_voie: integer
    complement_numero_voie: String
    type_voie: String
    nom_voie: String
    code_postal: String
    commune: String
    batiment: String
    nombre_logements_adresse_ipe: integer
    type_immeuble: String
    coordonnees: CoordonnesXY
    immeuble_neuf: integer
    reference_pm: String
    code_ban: String
    code_hexacle_voie: String
    information_complementaire_adresse: String
}
Adresse *--"1" CoordonnesXY

class AdresseRef {
    identifiant_immeuble: String
}
note right of AdresseRef: Seul l'identifiant d'immeuble\n est obligatoire sur \n l'adresse initiale

class AdresseComplementsSpecifiques {
    promoteur: String
    organisme_bailleur: String
    adresse_bailleur: String
    cp_bailleur: Integer
    ville_bailleur: String
    tel_bailleur: String
    siret_bailleur: String
    signature_convention: String
    date_signature_convention: Datetime
    reference_pbo: String
    adresse_pm: String
    coordonnees_pm: CoordonnesXY
}
Adresse <|-- AdresseComplementsSpecifiques
AdresseComplementsSpecifiques *--"1" CoordonnesXY

class CoordonnesXY {
    x: String
    y: String
    type: projection
}

legend
    |= Color |= Description |
    |<#Thistle>| Enumération de constantes|
    |<#FFFFFF>| Ressource exposée par l'API |
    |<#LightGrey>| Objet pointant vers une API (via id et href) |
    |<#Grey>| Objet propre à l'API  |
endlegend

@enduml
