@startuml

skinparam ParticipantFontColor automatic

title: CAS 5 : cas nominal SIMPLE INCOMPLET

autonumber

participant OC #Blue
participant OI #Green

== depot de fichier ==
OC->OI: Depot de la pièce jointe POST /tmf-api/attachment
OI --> OC: Identifiant du document
== creation anomalie adress ==
OC->OI: Création d'anomalie d'adresse \n POST /tmf-api/anomalieIPE
OI->OC: HTTP 201 indentifiant de l'anomalie
== creation du TT ==
OC->OI: Creation Trouble Ticket \n POST /tmf-api/troubleTicket/v4/troubleTicket \n {\n"name": "Compliant over last bill",\n"requestedResolutionDate": "2019-05-31T07:34:45.968Z",\n"severity": "Urgent",\n"ticketType": "Anomalie adresse",\n  "attachment": [\n    {\n      "mimeType": "image/png",\n      "name": "March Bill",\n      "url": "https://mycsp.com:7070/docloader?docnum=3534555"\n    }\n  ],\n  "relatedEntity": [\n    {\n      "id": "3472",\n      "href": "https://mycsp.com:8080/tmf-api/anomalieIPE297",\n      "@type": "RelatedEntity",\n      "@referredType": "AnomalieAdressCreation"\n    }\n  ],\n  "@type": "TroubleTicket"\n}

OI->OI: contrôles de surface

OI->OC: acquitement technique du dépot de ticket \n http201   {"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "Status":"acknoledged"}

alt abonnement aux notifications TT (n'est pas nécessaire à chaque ticket)
OC->OI:  \n POST https:\//myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/hub?Accept:application/json,{"callback":"http://OC.in.listner.com"}
OI->OC: acquittement de la souscription (avec son ID) \n http201:"Created, Content-Type: application/json, Location: /troubleTicket/hub/42{"id":"42","callback":"http://OC.in.listner.com","query":null}"

end
== Traitement du Ticket chez OI ==


OI->OI: contrôler l'accessibilité de la pj. et la recevabilité du ticket

OI->OC: acquitement fonctionnel du dépot de ticket (inProgress) \n { "eventId":"00002", "eventTime":"2022-10-12T11:42:25-04:00", "eventType":"TroubleTicketStatusChangeEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "status":"inProgress"}\n} \n}

OI->OI: detection des données manquantes dans le ticket, passage du ticket à pending \n\n PATCH /tmf-api/troubleTicket/v4/troubleTicket/100 {\n"ID":"100",\n"status":"pending",\n"statusChangeDate":"[horodatage]",\n"statusChangeReason":"merci de nous fournir les infos suivantes:.."}

OI->OC: notification de mise en pending : POST http://OC.in.listner.com/tmf-api/troubleTicket/v4/listener/troubleTicketStatusChangeEvent \n \n { "eventId":"00003", "eventTime":"2022-11-16T16:42:25-04:00", "eventType":"TroubleTicketResolvedEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "status":"pending"}\n} \n}

== Complement d'info du ticket par OC ==
OC->OI: Patch "anomalieAdresse"
note right #red
on n'a pas pris en compte le patch sur une anomalie.
 faut il la prendre en compte?
 ou OC mettre les infos dans les notes
endnote
OI->OC: Http 200

OC->OI: Passage à InProgess \n PATCH /tmf-api/troubleTicket/v4/troubleTicket/100 {\n"ID":"100",\n"status":"InProgess",\n"statusChangeDate":"[horodatage]",\n"statusChangeReason":"information fournie"}
== Reprise du ticket par OI ==
OI->OI: résolu, adresse ajoutée \n PATCH /tmf-api/troubleTicket/v4/troubleTicket/100 {\n"ID":"100",\n"status":"resolved",\n"statusChangeDate":"[horodatage]",\n"statusChangeReason":"résolu adresse ajoutée"}


OI->OC: notification de résolution: \n { "eventId":"00003", "eventTime":"2022-11-16T16:42:25-04:00", "eventType":"TroubleTicketResolvedEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "troubleTicketTicketStatusType":"resolved"}\n} \n}

== cloture du ticket par OC ==
OC->OI: valider la résolution \n PATCH /troubleTicket {\n"ID":"100",\n"status":"closed",\n"statusChangeDate":"[horodatage]",\n"statusChangeReason":"résolution acceptée"}


@enduml





